### ISSUE TITLE
<ojp:IncludeIntermediateStops>false</ojp:IncludeIntermediateStops> and Places

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#106]
A question, that may lead to some additional language in the standard.

If IncludeIntermediateStops is set to false, should the intermediate stops also be removed from Places in the Context? Or do we care?
e.g. here
![image](https://user-images.githubusercontent.com/24227470/94866520-d224a600-043f-11eb-8b66-4be22059c33b.png)
and here
![image](https://user-images.githubusercontent.com/24227470/94866591-f41e2880-043f-11eb-8231-09e26ae293aa.png)

**Comment by ue71603** [comment]
only context.

**Comment by ue71603** [comment]
Annoation for Context, Place object referenced in the result.

**Comment by pvgrumbkow** [comment]
Handled by pull request #107.
