### ISSUE TITLE
Usage of TSI PRM data?

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#108]
In the whole of the EC TSI PRM data at least for trains is manadatory and by now in a database. 
We discussed this with MENTz and for the routing with full accessibilty it is not enough.
Should we think about a filter? Or at least in adding the information to the context?
If you think so, we can prepare something.

**Comment by Aurige** [comment]
Yes, the TSI PRM is mainly focusing on stations, so it's not enough for a full routing where you will need the vehicle and vehicle to quay info.
However on the functional side, a fully accessible routing is definitely usefull. I think that can be prepared from the request filter side, but also on the trip description side (accessibility is highly dependent on the user: it is not always easy to tell him if the trip is accessible for him or not, but that's something he can decide on his own based on the provided trip description).

**Comment by pvgrumbkow** [comment]
May I ask, what you have in mind? The TripMobilityFilterGroup already contains filters for PRM requirements like "NoStairs" or "LevelEntrance". This should allow already accessible routing. On the trip description side, accessibility info can be transported via the Attributes.

**Comment by ue71603** [comment]
@pvgrumbkow  Do you think these are enough to cover TSI PRM? 
In Switzerland (as opposed to the general TSI PRM) we will also have some information for non-train stops in TSI PRM.

Also for the filters to work TSI PRM data needs to be loaded into the router. 

If there are no objections, we assume that the TripMobilityFilterGroup will be sufficient.

**Comment by Aurige** [comment]
To me there are plenty of other need: as filters, audio information, visual marking are probably in the minimum, but also staff availability, and more detailed information about equipment (doors and entry size, opening mechanism info, guidance strips, etc.).

When discussing with association involved in accessibility, they often tell that the basic wheel chair accessibility information is only "to ease one's conscience" but far from what is really expected, and forget about all other accessibility issues (note that there are quite often more blind people than wheel chairs in public transport, etc.).

It will of course take time before algoritms and data set will be avaible to fulfill all these needs, but it may be worth already integrating them in the API.

**Comment by pvgrumbkow** [comment]
Actually I don't know the detailed requirements of TSI PRM. But if they exceed the already existing filters and information attribute models, then I would propose to postpone this issue to v2.0. I have the impression, that detailed information rules and routing filters like Christophe indicate, would take too long for v1.1.

**Comment by ue71603** [comment]
Will be dealt with in https://github.com/VDVde/OJP/issues/187
