### ISSUE TITLE
Question:  StaySeated: How should a StaySeated be treated?

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#112]
OJP does currently not offer the possibility to tell a customer to stay seated. 
Should the two (or more Legs) be concatenated to make it clear or do we have two ore mor TimedLegs without a TransferLeg?
Or should we use a special TransferLeg (e.g. TransferMode=staySeated?

**Comment by pvgrumbkow** [comment]
The correct TransferMode for this is "remainInVehicle".

**Comment by ue71603** [comment]
Reading the whole enum would help ;.)
