### ISSUE TITLE
Add GeoPosition to intermediate stop points in trip response?

### ISSUE THREAD

**Issue by GerdC** [VDVde/OJP#119]
I implemented a Trias client and the stop points in the trip response have no GeoPosition. I see the same for OJP.

Since the app - like many others - always shows the (first) route on a map, I have lo make additional requests to get the coordinates of the stop points. This works, but it is an unnecessary burden for the server, it costs time, it drains battery on a mobile device and it adds cost for the data transferred on a mobile device.

I'd propose to add GeoPosition at least for intermediate StopPoints in the trip result. 

For consistence, this could also be done for LegBoard and LegAlight, though the coordinates can be deducted from the Projection Element.

Adding the stop point coordinates could be turned on/off by a parameter for those who don't need it.

**Comment by pvgrumbkow** [comment]
Within a TripResult (e.g. LegBoard, LegIntermediates, LegAlight) places are always only referenced. An OJP server should always return a TripRepsonseContext, containing all places, referenced within the actual TripResults.
So, as far as I see, your requested feature is already there.
