### ISSUE TITLE
Place needs a mandatory GeoPosition

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#120]
Currently Place needs a GeoPosition and GeoPosition needs Coordinates. We currently have points with no geo coordinates.

Possible solutions:
* Such points are bad and a problem, so it is right that you run into trouble
* GeoPosition 0:1
* GeoPosition 1:1, but an Unknown value for coordinates e.g. <GeoPosition><Coordinates>Unknown</Coordinates></GeoPosition>

What do you think?

**Comment by pvgrumbkow** [comment]
Actually, I would be really unhappy with places without a proper GeoPosition including coordinates. All discussion I had about this topic in the last ten years ended with "It is really lousy to have a place (which is a geographic object), which doesn't have any kinf of geographical reference, not even a barycentre." What would you do with such places in a map based environment?
I strongly vote for keeping GeoPosition including coordinates as mandatory.

**Comment by ue71603** [comment]
good for me.
