### ISSUE TITLE
OJP Discovery mechanism

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#121]
For LinkingAlps and perhaps for other things a discovery mechanism within OJP would perhaps be suitable.

You have the URL and you get:
* Covered lines
* Covered operators
* Last timetable load
* Real time availabe y/n
* Services offered
* Service when started etc

We have CheckStatusRequest/Response and CapabilitiesRequest/Response, but as far as I see, they are quite empty.

**Comment by pvgrumbkow** [comment]
You are looking for the capabilities of an already known service, right? Not for a discovery service like a service directory, correct?
As far as I know, CheckStatus and Capabilities are request types inherited from SIRI. For your purpose, we would have to fill them appropriately.
Looks for me like a version 2.0 feature.

**Comment by ue71603** [comment]
I am not sure, if we can fit it all into CheckStatus and Capabilties, but I will try and I agree, it is 2.0 stuff.

I am thinking that with EU sprint, LinkingAlsp etc, we should minimize the configurations that you should do. You should be able to point to an OJP router (URL, API-key) and then the systems should start integrating (at least that's my vision). Also it may be that multiple routers cover overlapping data areas.

**Comment by ue71603** [comment]
We do it as "paper" for the time being.

**Comment by ue71603** [comment]
Is now a PR #216
