### ISSUE TITLE
Question about OptimisationMethod

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#128]
We have trains that are dominated by other trains:
* T1 departes later than T2
* T1 arrives earlier than T2

This results in T2 never show up with any of the given OptimisationMethods (well leastCost would work, if we had implemented that). Both trains are direct. Our example Luzern - Bern.

So, what do you think: Do we need an additional OptimisationMethod=all, that does not optimise such TripLegs away?

**Comment by pvgrumbkow** [comment]
Hmm, what would an OptimizationMethod "all" mean? That you get one result, which fits best to an aggregation of the single optimization gains? Or one result for each OptimizationMethods? 
Actually, in your described case, our system would be able to return T2, if this is defined in the data. On the other hand, it wouldn't need an OptimizationMethod for this behaviour.
Thinking more general about the OptimizationMethod, I have the impression, that it doesn't fit to reality. In public transport the shortest geographical way is not relevant to the traveler. Actually, no criterion except the travel duration can be used alone to optimize a trip. Additionally there are several criteria which could be used in parallel.
Using our system as a role model, I could think of OptimizationMethod containing only "fastest", "earliestArrival", "latestDeparture", and "earliestArrivalAndLatestDeparture". Additionally I would introduce several "IncludeXXX" parameters like "IncludeTripsWithLessChanges", "IncludeTripsWithLessWalking", "IncludeCheaperTrips", "IncludeTripsWithLessOccupancy", "IncludeTripsWithReliefTrains".
This way clients could be more exact in what they request.

**Comment by ue71603** [comment]
We did also additional thinking. E.g. if you do multi-modal travel, then the complete private mode (car) must be included also.
We also thought about allDirectPT meaning that all public transport that connects directly to origin, (via) and destination. We have this problem also Bellinzona - Lugano (Ceneri tunnel vs moutain track).

**Comment by skinkie** [comment]
T2 will be visible by a _profile query_ starting before or at the departure time of T2. T2 could be suggested in a depart-now or get-me-the-hell-out-of-here optimisation.

**Comment by ue71603** [comment]
Matthias: Scenic
Stefan: Most scenic can be done with a score. Balances needed.

Will provide concrete example.

**Comment by ue71603** [comment]
superseeded by https://github.com/VDVde/OJP/pull/221
https://github.com/VDVde/OJP/issues/197
