### ISSUE TITLE
Documentation: Usage of groups in 4 columns

### ISSUE THREAD

**Issue by pvgrumbkow** [VDVde/OJP#135]
Currently the usage of groups within a structure uses only 2 columns, while the usage of elements with a type uses 4 columns. Groups should also use 4 columns. I propose to let the first column empty, the seconds contains the cardinality, the third the name of the group and the fourth empty again.
Several malformed tables seem to be caused by mixing group usage and element usage in one structure, e.g. in StopPlaceStructure.

**Comment by jmaerki** [comment]
Should be resolved with #154.

**Comment by trurlurl** [comment]
Removed *documentation* label - completed.
