### ISSUE TITLE
Extending PathGuidanceSection for accessibility/levels

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#145]
We have studied indoor routing through Transferleg. 
There it should be possible to tell people to move with an elevator to level -1 (and the like).
I didn't see that yet. 

Example:
![image](https://user-images.githubusercontent.com/24227470/103746136-e230c080-5000-11eb-96c3-35d2df47ddcb.png)

Should I create a description and a pull request? Or does there already exist work?

**Comment by StefanEngelhardt** [comment]
Our passive server is delivering those informations in a localized way in PathGuidanceSection/TrackSection/RoadName.

Examples:
                      <ojp:RoadName>Treppe abwärts zur Ebene -1</ojp:RoadName>
                      <ojp:RoadName>Rolltreppe abwärts zur Ebene -3</ojp:RoadName>

**Comment by ue71603** [comment]
concrete proposal

**Comment by ue71603** [comment]
FromLevelRef ToLevelRef in PathLink would be a possible place

**Comment by ue71603** [comment]
Also add some EquipmentStatus from NeTex to PathLink

**Comment by ue71603** [comment]
<xsd:simpleType name="EquipmentStatusEnumeration">
		<xsd:annotation>
			<xsd:documentation>Allowed values for status of EQUIPMENT.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:NMTOKEN">
			<xsd:enumeration value="unknown"/>
			<xsd:enumeration value="available"/>
			<xsd:enumeration value="notAvailable"/>
		</xsd:restriction>
	</xsd:simpleType>

**Comment by trurlurl** [comment]
This issue is followed up by PR#234 and can be closed. I don't seem to have the right permissions to do it.

**Comment by trurlurl** [comment]
Follow-up in PR #239.
