### ISSUE TITLE
XMLSpy notice due to imported namespaces without corresponding prefixes

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#148]
XML Spy is not really happy with the current OJP:
![image](https://user-images.githubusercontent.com/24227470/106431392-77db3680-646d-11eb-9576-fea8670e2d44.png)

Should we rethink this for version 2.0?

**Comment by sgrossberndt** [comment]
What exactly is XMLSpy unhappy about? If you apply the prefixes proposed by XMLSpy, how does the XSD look like? Could you please display and/or upload an example here?

**Comment by sgrossberndt** [comment]
@pvgrumbkow Isn't this probably the issue we just discussed in the meeting?

**Comment by sgrossberndt** [comment]
@ue

> 
> 
> What exactly is XMLSpy unhappy about? If you apply the prefixes proposed by XMLSpy, how does the XSD look like? Could you please display and/or upload an example here?

@ue71603 Could you please upload an example of XMLSpys proposed solution?

**Comment by ue71603** [comment]
I open ojp.xsd

**Comment by ue71603** [comment]
apply woodstock parser

**Comment by ue71603** [comment]
we will leave this be, as only happens with us and no other complaints.
