### ISSUE TITLE
TripRequest: Origin and Destination really 1:n?

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#149]
In 
![image](https://user-images.githubusercontent.com/24227470/106434737-3b5e0980-6472-11eb-86ac-fcb8608888d6.png)

Origin and Destination are unbounded.

Does anybody support this? Will anybody support it?
What will really happen?

Should we change this eventually?

**Comment by sgrossberndt** [comment]
Yes, this is definitely intentional, to allow multiple start and destination points to be specified and get the best route from one.

**Comment by pvgrumbkow** [comment]
Yes, this is intentional and HAFAS supports this in general. I assume, that also EFA supports it at least internally.

**Comment by schlpbch** [comment]
This puzzles me, assuming we have:

From 
- Madrid
- London

To
- Frankfurt
- Rom

What is the business need/use case for something like that? Do you really want to calculate the Cartesian product?
How do you display the result to the customer?

**Comment by sgrossberndt** [comment]
Adding additional context - the current (word) documentation states in **8.7.3.2 TripRequestStructure**:

> Usually, the elements Origin and Destination will appear as single child elements. Only in the case of multiple origin (or destination) points where each one has its own departure time (or arrival time) more than one origin (or destination) elements should be used in the TripRequest. In this case the responding system will choose the optimal origin-destination point pair that allows for an optimal entire trip. This choice may depend on time of day and could therefore be different with each delivered trip solution.

Regarding the calculation / performance issue: A system may, should and will respond with an error if the request exceeds its performance limitations.
