### ISSUE TITLE
Add refinement service to OJP from TRIAS

### ISSUE THREAD

**Issue by sgrossberndt** [VDVde/OJP#15]
[Low priority](https://github.com/VDVde/TRIAS/tree/Version1.4)
From Trias the TripRefineRequest should be copied. 

The other refinements I would skip for the time being. 

The goal of the refinement request could be:
* more information about certain legs (e.g. real-time, fares, more details, situations). 

In a distributed environment a trip planner may calculate based on timetables and then use refinement to update the trips from different services.

Some documentation could be copied from Trias for the doc.

**Comment by sgrossberndt** [comment]
This service from [TRIAS v1.2](https://github.com/VDVde/TRIAS) would be a useful addition to be ported to OJP 2.0.

**Comment by BertRadi** [comment]
Will be postponed to OJP 2.0

**Comment by ue71603** [comment]
@sgrossberndt @skinkie 
Should we include a TripRefinementRequest? For the other's I don't see really a use case.
In TripRefinement e.g. a responding system may add real time information. What do you think?

**Comment by skinkie** [comment]
https://www.vdv.de/431-2sdes-v-1-3.pdfx (page 149) defines what refinement means.

**Comment by ue71603** [comment]
* add realtime
* add fares
* has only references and must refine with product information
* enrichment
concept then PR
More requests needed.

**Comment by ue71603** [comment]
mergt
