### ISSUE TITLE
Documentation: create XSLT stylesheet to validate XSD conventions

### ISSUE THREAD

**Issue by jmaerki** [VDVde/OJP#153]
Create a separate XSLT stylesheet just to check some XSD conventions of this project such as the rule that no un-named complexTypes may be defined inside a named complexType.

**Comment by jmaerki** [comment]
Fully implemented. CI functionality needs to be tested once merged back into VDVde/OJP and into the master branch.

**Comment by sgrossberndt** [comment]
Works as advertised. To be seen in https://app.travis-ci.com/github/VDVde/OJP/builds/236193855
