### ISSUE TITLE
Service Discovery

### ISSUE THREAD

**Issue by BertRadi** [VDVde/OJP#16]

**Comment by sgrossberndt** [comment]
This service from [TRIAS v1.2](https://github.com/VDVde/TRIAS) would be a useful addition to be ported to OJP 2.0.

**Comment by ue71603** [comment]
@sgrossberndt  Do we need more than https://github.com/VDVde/OJP/pull/216? If not, could you please close this one?

**Comment by ue71603** [comment]
I think #216 does the trick.
