### ISSUE TITLE
xsd files that cannot be validated

### ISSUE THREAD

**Issue by stefanocudini** [VDVde/OJP#160]
I am trying to validate the xsd files defined in this repo, but I see that the XML xsd file used in the siri types has not been included in the right path, here:

https://github.com/VDVde/OJP/blob/92248dd09f85461f2f7a07375b3600afba2d2378/siri_utility/siri_types-v2.0.xsd#L3

also I was wondering which file to use to validate the input xml requests to a eventual entrypoint system

I thought about this:
https://github.com/VDVde/OJP/blob/master/OJP_Requests.xsd

**Comment by sgrossberndt** [comment]
The current release 1.0 does not validate (there are several issues IIRC).
We are currently in the process of preparing a new release 1.1 which validates (checked by Travis with xmllint). You can find the branch at https://github.com/VDVde/OJP/tree/changes_for_v1.1
