### ISSUE TITLE
ErrorMessage --> Problem (RfC 7807)

### ISSUE THREAD

**Issue by schlpbch** [VDVde/OJP#167]
There's an internet standard to model  to carry machine-readable details of errors 

https://datatracker.ietf.org/doc/html/rfc7807

The proposal is to use  "Problem" instead of "ErrorMessage". This also facilitates the implementation of OJP in REST.

**Comment by ue71603** [comment]
@skinkie  would like from @schlpbch  what he wants to achieve with this.

**Comment by ue71603** [comment]
we would have to change SIRI for that.

**Comment by ue71603** [comment]
Will add this to SIRI github and leave it there.

**Comment by ue71603** [comment]
Added to SIRI list: https://github.com/SIRI-CEN/SIRI/issues/102
