### ISSUE TITLE
Inconsistency in PlaceStructure and PlaceTypeEnumeration

### ISSUE THREAD

**Issue by schlpbch** [VDVde/OJP#168]
![PlaceStructure-PlaceTypeEnumeration](https://user-images.githubusercontent.com/18540761/125785180-32ba3bd9-995a-4851-8007-0ddde605eada.GIF)

**Comment by schlpbch** [comment]
Questions:

- Do "StopPlace" and "StopPoint" both map to "stop"  
- Does "GeoPosition" map to the  "coord" enum? Better: "geoPosition"

**Comment by ue71603** [comment]
Addressed in: https://github.com/VDVde/OJP/pull/218
