### ISSUE TITLE
Resolve the infinite loop in the documentation

### ISSUE THREAD

**Issue by skinkie** [VDVde/OJP#172]
As brought up in #165 by @schlpbch. Not a show stopper, but we may think about a solution about it.

> ![image](https://user-images.githubusercontent.com/502394/130767388-ebc7d4f5-5966-4cba-b852-10603e6e9269.png)
> This suggests that PointOfInterestRef is of type PointOfInterestRef which would be an infinite loop.

@jmaerki replied:
> Yes, that's a consequence of the documentation rules where I remove the "Structure" Suffix. How would you expect this to be resolved? I can't just remove the "Ref" at the end because that would create another conflict between "PointOfInterestRef", "PointOfInterestRefStructure" and "PointOfInterest". Same for "TopographicPlace*". The only way out is to remove the rule that removes the "Structure" Suffix.

**Comment by ue71603** [comment]
The answer of Jeremias is there. The linking in HTML is correct, but in prose strange. He suggests that we change our decision  to remove the "structure" suffix in the second column. @sgrossberndt @skinkie  Can you think what we should do?

**Comment by ue71603** [comment]
Stefan: Having name+structure as anchor tag, but not on screen.

**Comment by ue71603** [comment]
In principle same solution as in: https://github.com/VDVde/OJP/issues/189

**Comment by ue71603** [comment]
We keep (currently) to the agreed Siri - "standard" the + says it is a structure.

**Comment by ue71603** [comment]
Add titel tag linked that contains the name with Structure still there.

**Comment by sgrossberndt** [comment]
For table definition see https://www.vdv.de/431-2sdes-v-1-3.pdfx "3 Notation of XML elements and structures" "3.1.4 Data type"

**Comment by sgrossberndt** [comment]
Looks good. Will add a pull request.

**Comment by sgrossberndt** [comment]
As the change is within your own repository and not available as a branch in [OJP](https://github.com/VDVde/OJP) it seems I cannot create a pull request from it honoring your work, @jmaerki.

**Comment by ue71603** [comment]
Can't we grab it from his branch. Stephan will do it (one line)

**Comment by sgrossberndt** [comment]
Merged in https://github.com/VDVde/OJP/pull/233
