### ISSUE TITLE
Schema Location better? and really available?

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#176]
In our serve we currently provide:

<siri:OJP xmlns:siri=http://www.siri.org.uk/siri xmlns:ojp=http://www.vdv.de/ojp version="1.0">
    <siri:OJPResponse>
        <siri:ServiceDelivery>
            <siri:ResponseTimestamp>2021-11-26T17:40:30Z</siri:ResponseTimestamp>
            <siri:ProducerRef>OJPCH_Prod</siri:ProducerRef>
            <siri:Status>true</siri:Status>
            <ojp:OJPTripDelivery>

However, neither xsd exists really at that location. I know this is not uncommon. But should we do better?
What does the group think?

**Comment by derhuerst** [comment]
I think it would be great to have the schema be available at its canonical URL! This aligns the spec closer with the Linked Data principle of using machine-readable and -discoverable identifiers for schemas (or types within schemas).
