### ISSUE TITLE
trip.tripLegs to trip.legs

### ISSUE THREAD

**Issue by schlpbch** [VDVde/OJP#180]
Having `trip.tripLegs` is redundant, please rename to `trip.legs` with OJP 2.0. Makes it also more complaint with **transmodel**.

I can provide a patch if necessary.

**Comment by ue71603** [comment]
@schlpbch  unclear what should be changed. TripLeg -> Leg. There is no tripLegs element. And for TripLeg I think it is clearer.

**Comment by ue71603** [comment]
TripLeg --> Leg
