### ISSUE TITLE
More simplications

### ISSUE THREAD

**Issue by schlpbch** [VDVde/OJP#183]
address.addressCode --> address.code
address.addressName --> address.name
pointOfInterest.pointOfInterestCode --> pointOfInterest.code
pointOfInterest.pointOfInterestName --> pointOfInterest.name

**Comment by ue71603** [comment]
We will have to look what it really is in NeTEx and Siri as well.

**Comment by ue71603** [comment]
done with PR https://github.com/VDVde/OJP/pull/217
