### ISSUE TITLE
What is OJP and what is the CEN SIRI relation?

### ISSUE THREAD

**Issue by dancesWithCycles** [VDVde/OJP#184]
Hi folks,
Thank you so much for providing and maintaining this repository. I am new to CEN SIRI and studying everything that I can get hold on. This is how I learned about OJP.

* I would like to know what I can use OJP for and how?
* Moreover, I would like to know how OJP is using SIRI interfaces?

I am also looking for SIRI implementations. 

For instance, I am providing GTFS-RT feeds that I want to convert into a Vehicle Monitoring feed (SIRI-VM). I also know about SIRI-SX feeds that I want to consume.

I would appreciate any hints in this direction.

Cheers!

**Comment by ue71603** [comment]
OJP is an interface specification for a generic trip planner. Some elements are aligned with Siri (same elements and name space). All are part of the CEN Transmodel ecosystem https://www.transmodel-cen.eu/. Many OJP realisations use SIRI in the background to get the information they deliver then in the responses (e.g. estimated arrival times and the like).

Siri is a separate project that does different real time data transfers (as I think you found out already).  Siri is more of something a bigger "user" like a trip planer consumes from data sources.  In itself the OJP services and Siri services are usually completly separated.

Does this help?

**Comment by dancesWithCycles** [comment]
Hi @ue71603 ,
Thank you so much for sharing your OJP insights. That sounds that I can not use OJP to consume or produce SIRI services Vehicle Monitoring or Situation Exchange. Can you confirm? Do you know any existing open source software to do this job?

Cheers,

Stefan

**Comment by ue71603** [comment]
We are currently in the development phase of a piece of software that will consume SIRI SX to feed a small app. but there the feed is SIRI SX to start with (also SIRI ET/PT). GTFS-RT 2 SIRI I don't know of anything. Do you @skinkie ? 
(Usually it is done the other way around). 

But perhaps we should think about a converter from GTFS-RT 2 SIRI .
Cheers Matthias

**Comment by skinkie** [comment]
> That sounds that I can not use OJP to consume or produce SIRI services Vehicle Monitoring or Situation Exchange. 

Indeed this is absolutely not the intention of OJP. OJP would be an API definition towards your journey planner, the data you use to feed a journey planner is SIRI-ET. The data you use to feed an integration platform is either SIRI-VM or SIRI-ET (precomputed).

> Can you confirm? Do you know any existing open source software to do this job?

What task do you want to achieve with SIRI ET or VM?

**Comment by dancesWithCycles** [comment]
> We are currently in the development phase of a piece of software that will consume SIRI SX to feed a small app. but there the feed is SIRI SX to start with

Hi @ue71603 ,
That sounds like synergy. I also have a SIRI SX feed that I want to consume. Can I join in this activity?

**Comment by dancesWithCycles** [comment]
> What task do you want to achieve with SIRI ET or VM?

Hi @skinkie ,
Thank you so much for clarification. At the moment I am rathe occupied with SIRI VM and SX. Anyhow SIRI *whatever service feed* could come later.

* One data source is a GTFS-RT feed and the other is a Automatic Vehicle Location (AVL) system. No matter which data source, I would like to convert it to SIRI VM and offer that feed any consumer.
* A transportation authority is producing and offering SIRI SX feeds. I am eager to test and validate any app that is able to consume it.

Does this sound like anything you are familiar with? Do you know any software that would suite this purpose?

Cheers,

Stefan

**Comment by skinkie** [comment]
Lets say the integration platform @skywave is building does the anything in anything conversion for us at this moment.

**Comment by dancesWithCycles** [comment]
> Lets say the integration platform @skywave is building does the anything in anything conversion for us at this moment.

Hi @skinkie ,
is this software open source? I can not find any links or repositories.

**Comment by skinkie** [comment]
The previous iteration is, but does not support SIRI. https://github.com/bliksemlabs/bliksemintegration-realtime

**Comment by dancesWithCycles** [comment]
Please let me know, if you plan to develop the current iteration or any other SIRI related software out in the public. In this case, I'll checkout how myself, my company, or the open source transport community can support your activity. I appreciate this exchange of thoughts.

Cheers,

Stefan

**Comment by skinkie** [comment]
@dancesWithCycles can you send me an email? stefan at opengeo dot nl
