### ISSUE TITLE
Documentation: Headers of chapters should contain permalinks

### ISSUE THREAD

**Issue by sgrossberndt** [VDVde/OJP#189]
Currently the headers of the chapters like sequences and groups contain ids so its possible to create a link to jump to the anchor, e.g.:
https://vdvde.github.io/OJP/generated/OJP.html#PrivateCodeStructure
Currently you have to find the link in the table of contents or extract it from the source or guess it.
Instead the header should have a perma-link symbol appended (e.g. like in [TYPO3-Documentation](https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/SiteHandling/CreateNew.html#creating-a-new-site-configuration)) so you can click on it to have the perma-link to this specific element available easily.

**Comment by ue71603** [comment]
Jeremias said, it should be simple and he would implement a parameter. This we could give him. @sgrossberndt  Do you coordinate with him, if necessary?

**Comment by ue71603** [comment]
Stephan: Would prefer a different approach. I am still thinking about that.

**Comment by sgrossberndt** [comment]
Merged in https://github.com/VDVde/OJP/pull/246
