### ISSUE TITLE
Describe horseshoeproblem in the specification document and how to solve it (keep the data)

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#190]
Will be done as a chapter in the specification document. 
You just write a chapter and we will then integrate it. Save it here: https://vdvde.sharepoint.com/:f:/r/sites/CENTC278WG3SG8OJP/Freigegebene%20Dokumente/General/Version_2.0?csf=1&web=1&e=NW80do

Use the current 1.1 document as a basis (to make sure that the formatting is the same):  Template: https://vdvde.sharepoint.com/:w:/r/sites/CENTC278WG3SG8OJP/Freigegebene%20Dokumente/General/Version_1.1/210713-OJP-64_e_stm-1.1%20-%20revised.docx?d=we6a009d6f57e4f4bb7e206a48f731422&csf=1&web=1&e=avghar

**Comment by ue71603** [comment]
Claus: Adding data only works for the timetable part. Real time must always be done with the "master" system. 
Andreas: The realtime is done with refinement and always in the relevant system.
Andreas: Only add relevant journeys to avoid horse shoe. Not necessary to load everything.

Andreas: Still updating.

**Comment by ue71603** [comment]
André: Is adding the timetables contradictory to distributed trip planning? 
Andreas: Then you have have the horseshoe problem.
André: Wouldn't it be possible to mark when a horseshoe might occur. Then it could be added as a possible solution. Results of an extension already in a single "passive" system.
Claus: Add all timetable data again and again is a bit harder.  Also for timetable details. 
André: If we have Lugano and Merano. And you add a planning line which is only use to determine that there is a horseshoe. Then you switch to distributed search.
Malte: Might help.

**Comment by ue71603** [comment]
Malte: wie stellst du dir den Ablauf des Horseshoe-Problems vor? Die Auskunft findet die Fahrt, die sie bisher findet, aber erkennt, dass diese eventuell nicht optimal ist?
Ich würde vorschlagen die TripStatusGroup um ein entsprechendes Element (Estimated, provisional, toBeRefined, ...) zu erweitern:
![image](https://user-images.githubusercontent.com/24227470/186894672-4124b2ec-be20-42e7-ac9d-d5e5f09bb059.png)

**Comment by ue71603** [comment]
Andreas: Ich hab mal die Vorläufige Version der Beschreibung des Horseshoe Problems: https://vdvde.sharepoint.com/:f:/r/sites/CENTC278WG3SG8OJP/Freigegebene%20Dokumente/General/Version_2.0?csf=1&web=1&e=NW80do

**Comment by ue71603** [comment]
Reviewed the documents. It now contains some comments.

**Comment by AndreasAtSBB** [comment]
I did change the description of the solutions: 
https://vdvde.sharepoint.com/:w:/r/sites/CENTC278WG3SG8OJP/Freigegebene%20Dokumente/General/Version_2.0/[220812-OJP-Horseshoe_problem.docx](https://vdvde.sharepoint.com/:w:/r/sites/CENTC278WG3SG8OJP/Freigegebene%20Dokumente/General/Version_2.0/220812-OJP-Horseshoe_problem.docx?d=wab155f40de9f49819bacafec0829b05b&csf=1&web=1&e=rYn68b)?d=wab155f40de9f49819bacafec0829b05b&csf=1&web=1&e=rYn68b

**Comment by ue71603** [comment]
Moved it into the active/passive paper. So I close it here.
