### ISSUE TITLE
Chapter on active/passive server relationships

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#191]
* Process the document from VAO .. DONE, not yet documented
* Having a discussion with Roberto (STA)
* Copying things from Confluence .. DONE
* Having a discussion with MENTZ/HaCon/Geops

**Comment by ue71603** [comment]
Started here: https://vdvde.sharepoint.com/sites/CENTC278WG3SG8OJP/Freigegebene%20Dokumente/General/Version_2.0/210713-OJP-65_e_active_server.docx?web=1

**Comment by derhuerst** [comment]
General question: Is it possible to view this draft a) without logging in, and b) without being in the `vdvde` organisation?

**Comment by ue71603** [comment]
@derhuerst  CEN drafts are strictly confidential within the work group. However, the XSD changes are all documented fully and can also be understood through the Pull Requests. So for the documentation purposes off "normal users". It is advised to use the XSD, the examples and some implementation notes we will provide. The Sharepoint link is for the people doing the work and unfortunately not for public consumption.

**Comment by ue71603** [comment]
@derhuerst  However, One of the things we are discussing is, that this explanation will be part of a separate document and then we will publish it. We probably we will do that. However, not yet done.

**Comment by ue71603** [comment]
New version done. Currently in review with Andreas Glauser and Stefan de Konink. Will be presented in November

**Comment by ue71603** [comment]
not as part of the standard

**Comment by derhuerst** [comment]
Is the new version publicly accessible?

**Comment by ue71603** [comment]
It will be :-) will link it here (and in the readme.md)
