### ISSUE TITLE
Revisit Availability after the latest revision of TRIAS

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#196]
TRIAS 1.4 has been finalised. It needs to be checked, if Availability did not change. If it did, we need to update the new Availability Request. It also needs to be documented in the word doc. https://github.com/VDVde/TRIAS/tree/Version1.4

**Comment by ue71603** [comment]
@herlitze  Can we get the latest version to see, what we need to update in the AvailabilityRequest. Can you afterwards assign it to @trurlurl

**Comment by herlitze** [comment]
The changes are part of TRIAS version 1.4, the xsd can be downloaded under https://github.com/VDVde/TRIAS/tree/Version1.4

**Comment by ue71603** [comment]
Check should be possible.

**Comment by trurlurl** [comment]
@herlitze Could you please have a look at the proposed changes in the availabilityRequest branch? 
In particular the questions (marked *TODO") regarding the ticket and bookable services information in the response.

I'll then finalize the proposal according to your feedback and create a PR. Or shall I already create the PR and you work there?

**Comment by trurlurl** [comment]
Continued in #241.
