### ISSUE TITLE
OJP.xsd is still failing to generate JAXB

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#202]
Hello Stefan

After your update notes I updated my branch with the latest github master.

Unfortunately I can’t still build ☹

I attached the part of my pom.xml that cares about building the JAXB POJO’s. Please try to execute the downloaded code https://github.com/VDVde/OJP.git with this sample pom -> if you succeed, I will gladly give it another try. 

1)	I get the following fault:
a.	.1\siri\siri_reference-v2.0.xsd (Das System kann die angegebene Datei nicht finden)
C:\Users\u210875\IdeaProjects\journey-service_2nd\journey-service-ojp-adapter\src\main\resources\ojp-1.0.1\OJP_Fare.xsd [5:102]: java.io.FileNotFoundException:
b.	If I correct the schema file to where it seems to be: schemaLocation="./siri/siri_reference-v2.0.xsd
i.	“./siri_model I get fault 2) which is even worse…

2)	  There is already a class… Guess the reference was built already and there is cyclic problem..?
a.	[ERROR] C:\Users\u210875\IdeaProjects\journey-service_2nd\journey-service-ojp-adapter\src\main\resources\ojp-1.0.1\siri_model\siri_reference-v2.0.xsd [307:52]: Eine Klasse/Schnittstelle mit demselben Namen "main.java.ojp.model.ContinuousModesEnumeration" wird bereits verwendet. Verwenden Sie eine Klassenanpassung, um diesen Konflikt zu l�sen.
b.	org.xml.sax.SAXParseException; systemId: file:/C:/Users/u210875/IdeaProjects/journey-service_2nd/journey-service-ojp-adapter/src/main/resources/ojp-1.0.1/siri_model/siri_reference-v2.0.xsd; lineNumber: 307; columnNumber: 52; Eine Klasse/Schnittstelle mit demselben Namen "main.java.ojp.model.ContinuousModesEnumeration" wird bereits verwendet. Verwenden Sie eine Klassenanpassung, um diesen Konflikt zu l�sen.
            at com.sun.tools.xjc.util.CodeModelClassFactory.createClass(CodeModelClassFactory.java:92)
            at com.sun.tools.xjc.
[pom_SAMPLE.zip](https://github.com/VDVde/OJP/files/8793354/pom_SAMPLE.zip)
util.CodeModelClassFactory.createClass(CodeModelClassFactory.java:63)
            at com.sun.tools.xjc.generator.bean.BeanGenerator.generateEnumDef(BeanGenerator.java:599)
            at com.sun.tools.xjc.generator.bean.BeanGenerator.<init>(BeanGenerator.java:156)
            at com.sun.tools.xjc.generator.bean.BeanGenerator.generate(BeanGenerator.java:141)
            at com.sun.tools.xjc.model.Model.generateCode(Model.java:258)
            at org.apache.cxf.maven_plugin.XSDToJavaRunner.run(XSDToJavaRunner.java:179)
            at org.apache.cxf.maven_plugin.XSDToJavaRunner.main(XSDToJavaRunner.java:360)

Regards
Peter

**Comment by skinkie** [comment]
From my perspective this repository creates a nice model. Please close when agreed.

https://github.com/bliksemlabs/ojp-java-model

**Comment by ue71603** [comment]
added to wiki page
