### ISSUE TITLE
reconstructionContext

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#210]
Hafas has a reconstructionContext to be stateless. We should think about the use case and the realisation of such a reconstructionContext. This is needed to get updates on the whole trip and not only a vehicle or a journey.  
Single vehicle and journey don't show if the chain breaks. 

«"¶HKI¶T$A=1@O=Biel/Bienne@X=7242915@Y=47132898@u=0@L=8504300@a=128@$A=1@O=Zürich HB@X=8540211@Y=47378177@u=0@L=8503000@a=128@$202203091017$202203091130$IC 5    $$1$$$$¶KC¶#VE#0#CF#100#CA#0#CM#0#SICT#1#¶KCC¶#VE#0#ERG#1#HIN#0#ECK#128777|128777|128850|128850|0|0|165|128772|1|-2147479534|0#")

What is the idea of the others on how to deal with it.

Perhaps we should use TripRequest instead of TripInformationRequest for this.

**Comment by ue71603** [comment]
Dirk: Contains in principle also trip information. Trip can be reconstructed. For Fare calculation it should be simple. 
Stefan: Is it different that just storing a serialized format.
@normanoffel : Can we have some insights what HaCon is doing with it?

**Comment by dirkweisser** [comment]
[09:49] Dohmen, Claus | VDV
Does the reconstructionContext really contain the information on the trip DIRECTLY or is it "only" a reference to the trip, which is stored somewhere else? Makes important difference with regard to  server side parallelization / load balancing.

**Comment by ue71603** [comment]
Malte: I need input, what the context really is.

**Comment by pvgrumbkow** [comment]
HAFAS' reconstruction context contains information, which enables HAFAS to reconstruct the trip. However, the trip is neither stored anywhere, nor is all its information contained in the context, nor any other system than HAFAS is intended to interpret the context. You need a HAFAS and its database to restore the trip by the help of the context.
Actually, I'm not sure about this use case within a standard API. Seen from outside of HAFAS, the context is used like a unique ID for a trip. Then why don't we use it that way? Why would we need an extra element for the HAFAS context? The only reason, which comes into my mind is, that some system expect IDs to be not very long.
Adding another element for the context would lead to HAFAS filling short fake trip IDs and the context. What's won with that?

I correct my input: I don't think that this kind of context is of any good within a standard API.

**Comment by ue71603** [comment]
Closed after discussion with @pvgrumbkow
