### ISSUE TITLE
Adding OrganisationRefs to PlaceResult for Taxi and demand-responsive area based offers

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#212]
For Taxi and other area based modes the OperatorRefs in the answer to PlaceInformationRequest are crucial to find out, which operators can be used (this may be dozens).

Adding 0-inf: OrganisationRefs
The OrganisationRefs can then be used for AvailabilityRequests, Booking and the like
![PlaceResult](https://user-images.githubusercontent.com/24227470/178004508-1d7b127b-354d-48b0-9395-1610339978fb.PNG)

Eventually also ContinuousServiceGroup should also contain OrganisationRefs (saying, if a walk can be replaced by sharing, taxi etc etc.

We perhaps need the Organisations in the Context with information about their mode.

What do you think?

**Comment by trurlurl** [comment]
Removed *documentation* label - documentation will be done for the pull request.
