### ISSUE TITLE
PlaceContextStructure/IndividualTransportOptions lacks siri:PrivateModeChoiceGroup

### ISSUE THREAD

**Issue by BertRadi** [VDVde/OJP#23]

**Comment by skinkie** [comment]
Could be fixed by #2

**Comment by pvgrumbkow** [comment]
Proposal: Split up the issue into 2 issues.
- Input to SIRI, that PrivateModeChoiceGroup should be extended by a "OwnVehicleSubmode" containing modes like "walk", "ownBike", "ownCar".
- Extend in OJP IndividualModesEnumeration by sensible modes from the siri:PrivateModeChoiceGroup.

**Comment by sgrossberndt** [comment]
https://github.com/SIRI-CEN/SIRI/blob/integration/xsd/siri_model/siri_modes-v1.1.xsd#L90

**Comment by ue71603** [comment]
@pvgrumbkow  can we close this issue? As the pull request was handled.
