### ISSUE TITLE
TripResponse: How to handle multiple responses for sharing etc

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#245]
* Extend response so that it can handle operator or things like that.
*

**Comment by AndreasAtSBB** [comment]
A more detailed description which maybe integrated in the OJP 2.0 document later on is here:
https://vdvde.sharepoint.com/:f:/r/sites/CENTC278WG3SG8OJP/Freigegebene%20Dokumente/General/Version_2.0?csf=1&web=1&e=NW80do

Document: https://vdvde.sharepoint.com/:w:/r/sites/CENTC278WG3SG8OJP/Freigegebene%20Dokumente/General/Version_2.0/221003-OJP-Gap%20analysis%20OJP%202.0%20for%20TR%20with%20multimodal%20trips.docx?d=wce3e3fbd937449ed80b615c70b85add8&csf=1&web=1&e=MGyeQX

Document is basis for further discussions and open for modification and inputs.

**Comment by AndreasAtSBB** [comment]
I made a new document which should describe the way of how the process works from the first request how to get to the final user customised trip. 
As defined the first request should deliver the PT answer and possible options at origin and destination.
Final document should explain it on an example for bike sharing and ODV.
Here is the document: https://vdvde.sharepoint.com/:w:/r/sites/CENTC278WG3SG8OJP/Freigegebene%20Dokumente/General/Version_2.0/221129-OJP%202.0%20Implementation%20tips%20for%20multimodal%20trips.docx?d=weceeec5fffcb4a1bbd35701e2a2f1328&csf=1&web=1&e=dzc2X7
@herlitze can you add missing things where I put a red text in?

**Comment by herlitze** [comment]
> @herlitze can you add missing things where I put a red text in?
Yes, I will take a look.

**Comment by ue71603** [comment]
Commented. Needs rework before the meeting.

**Comment by AndreasAtSBB** [comment]
Rewerk made, especially the cleanup. Maybe other details needs to be added. 
Let's discuss it.
Discussing paper no longer needed. Just "Implementation tips for multimodal trips.docx" needs a further look at.

**Comment by ue71603** [comment]
Discussion 15.12:
* Andreas presents the idea (multiple variantes requested in one and giving results)
* Malte: We think you give one mode and you get multiple operators for that mode.
* Andreas: Sometime a single leg can be replaced by a different operator. But for other modes one needs to recalculate the whole trip.
* Matthias: Detailed examples needed (from the user journey perspective)
* Andreas: User knows origin and destinations, but he does not have a clue about the options at the beginning and the end.
* Malte: That is not the problem to have multiple requests. 
* Andreas: I want to know if ODV exists.  LIR at origin and destination is needed. For each option it is needed. For every option different radius is necessary to take into account. Radius differently to take into account.
*  Malte: What is OJP to be used. There might be a layer between the client and the OJP that can send separate requests to the router and get information from several requests and building those together.  I don't believe in one request doing it all for the client. The "Client" ist rather powerful and has a lot of business logic. 
* Stefan: I agree.  I would use RefinementRequest for a specific part or for the full TripRequest. Only a selection.  Booking is sent to the server again. 
* Malte: Two LIR, then a general "TripRequest" per Mode (depending on tabs) and a finer one with concrete operators if the tab is actived.

**Comment by ue71603** [comment]
Next version will be done by Andreas and Matthias

**Comment by ue71603** [comment]
@AndreasAtSBB : When do we have a version to discuss?

**Comment by ue71603** [comment]
Current version: https://vdvde.sharepoint.com/sites/CENTC278WG3SG8OJP/Freigegebene%20Dokumente/General/Version_2.0/221129-OJP%202.0%20Implementation%20tips%20for%20multimodal%20trips.docx?web=1
Andreas and I will discuss it on 9.1.2023

**Comment by AndreasAtSBB** [comment]
Bassed on disscusions i did update the document: https://vdvde.sharepoint.com/sites/CENTC278WG3SG8OJP/Freigegebene%20Dokumente/General/Version_2.0/221129-OJP%202.0%20Implementation%20tips%20for%20multimodal%20trips.docx?web=1
There are still points, where further details will be needed.

**Comment by AndreasAtSBB** [comment]
I made a new cleand up copy, after the workshop from today: https://vdvde.sharepoint.com/:w:/r/sites/CENTC278WG3SG8OJP/Freigegebene%20Dokumente/General/Version_2.0/230203-OJP%202.0%20Implementation%20tips%20for%20multimodal%20trips%20v2.0.docx?d=w5c915d3823b540fb95759debbb9c313c&csf=1&web=1&e=Xkcp4F

If someone miss something from the old documents, just copy it again from the documents in the archive folder: 
https://vdvde.sharepoint.com/:f:/r/sites/CENTC278WG3SG8OJP/Freigegebene%20Dokumente/General/Version_2.0/[Archiv](https://vdvde.sharepoint.com/:f:/r/sites/CENTC278WG3SG8OJP/Freigegebene%20Dokumente/General/Version_2.0/Archiv?csf=1&web=1&e=JqqCe1)?csf=1&web=1&e=JqqCe1

**Comment by AndreasAtSBB** [comment]
I did update the document according to actual comments.

**Comment by AndreasAtSBB** [comment]
Documentation needs to be addapted, because of the desition from issue #352 to add a new service and the desiction to use this also for operator selection. 
I'll do that ASAP.

**Comment by AndreasAtSBB** [comment]
I did update the file, not yet finished, sepcially the pictures need som changes (text in pictures).

**Comment by ue71603** [comment]
@AndreasAtSBB  Is this finalized? We could give it to Christine to make the white paper ready for publication.

**Comment by AndreasAtSBB** [comment]
Document updated with graphics which were to change after last CEN meeting.

**Comment by ue71603** [comment]
result is here https://www.oev-info.ch/sites/default/files/2024-06/whitepaper_sharing_2024-04-05.pdf
