### ISSUE TITLE
Update SIRI

### ISSUE THREAD

**Issue by sgrossberndt** [VDVde/OJP#25]
Update SIRI to most recent version in order to fix issues with xmllint and fix bugs

**Comment by sgrossberndt** [comment]
SIRI was created as a repository of its own in https://github.com/VDVde/SIRI with the most recent release 2.0o. OJP should reference that as a git submodule instead of bringing those files as its own. We need to make sure though the zip download of releases does contain the siri files too.

**Comment by tim-rivett** [comment]
this should ideally reference the now official SIRI Git Hub at:
https://github.com/SIRI-CEN/SIRI

**Comment by ue71603** [comment]
Which version of Siri will we use in 1.1? And should we not close either #25 or #56 (or have #25 for 1.1 and #56 for 2.0)

**Comment by sgrossberndt** [comment]
I propose to update to SIRI v2.0q in v1.1 manually using https://github.com/SIRI-CEN/SIRI/releases/tag/v2.0q and set up SIRI as git submodule from upstream https://github.com/SIRI-CEN/SIRI for OJP v2.0 in https://github.com/VDVde/OJP/issues/56

**Comment by sgrossberndt** [comment]
We decided to skip the update to to SIRI v2.0q in v1.1 to avoid breaking anything related to SIRI. In OJP v2.0 we want to set up SIRI as git submodule from upstream https://github.com/SIRI-CEN/SIRI using the soon to be released new SIRI version currently available in the [integration](https://github.com/SIRI-CEN/SIRI/tree/integration) branch.
This will be tracked in #56 and thus I am closing this issue.
