### ISSUE TITLE
Occupancy information

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#250]
Check if siri:Occupancy is really up to date.

OJP:

> 		<xs:element name="Occupancy" type="siri:OccupancyEnumeration" minOccurs="0">
>				<xs:annotation>
>					<xs:documentation>[equivalent to OCCUPANCY in SIRI] passenger load status of a VEHICLE. If omitted, not known.</xs:documentation>
>				</xs:annotation>
>			</xs:element>

Definition Siri:
>	<xsd:simpleType name="OccupancyEnumeration">
>		<xsd:annotation>
>			<xsd:documentation>Passenger load status of a VEHICLE.</xsd:documentation>
>		</xsd:annotation>
>		<xsd:restriction base="xsd:NMTOKEN">
>			<xsd:enumeration value="full"/>
>			<xsd:enumeration value="seatsAvailable"/>
>			<xsd:enumeration value="standingAvailable"/>
>		</xsd:restriction>
>	</xsd:simpleType>

NeTEx has a more detailed Capacity model:
>	<xsd:group name="CapacityGroup">
>		<xsd:annotation>
>			<xsd:documentation>Elements for a PASSENGER CAPACITY REQUIREMENT. relevant for passenger systems.</xsd:documentation>
>		</xsd:annotation>
>		<xsd:sequence>
>			<xsd:element name="TotalCapacity" type="NumberOfPassengers" minOccurs="0">
>				<xsd:annotation>
>					<xsd:documentation>The total capacity of vehicles of the type.  For a requirement this is the minimum needed.</xsd:documentation>
>				</xsd:annotation>
>			</xsd:element>
>			<xsd:element name="SeatingCapacity" type="NumberOfPassengers" minOccurs="0">
>				<xsd:annotation>
>					<xsd:documentation>The seating capacity of vehicles of the type. For a requirement this is the minimum needed.</xsd:documentation>
>				</xsd:annotation>
>			</xsd:element>
>			<xsd:element name="StandingCapacity" type="NumberOfPassengers" minOccurs="0">
>				<xsd:annotation>
>					<xsd:documentation>The standing capacity of vehicles of the type.  For a requirement this is the minimum needed.</xsd:documentation>
>				</xsd:annotation>
>			</xsd:element>
>			<xsd:element name="SpecialPlaceCapacity" type="NumberOfPassengers" minOccurs="0">
>				<xsd:annotation>
>					<xsd:documentation>The number of special places on vehicles of the type, e.g. seats for the disabled. For a requirement this is the minimum needed.</xsd:documentation>
>				</xsd:annotation>
>			</xsd:element>
>			<xsd:element name="PushchairCapacity" type="NumberOfPassengers" minOccurs="0">
>				<xsd:annotation>
>					<xsd:documentation>The number of push chair places on vehicles of the type. For a requirement this is the minimum needed.</xsd:documentation>
>				</xsd:annotation>
>			</xsd:element>
>			<xsd:element name="WheelchairPlaceCapacity" type="NumberOfPassengers" minOccurs="0">
>				<xsd:annotation>
>					<xsd:documentation>The number of wheelchairs places on vehicles of the type. For a requirement this is the minimum needed.</xsd:documentation>
>				</xsd:annotation>
>			</xsd:element>
>		</xsd:sequence>
>	</xsd:group>

Do we need to extend it? Or is this part of a formation service or the like?

**Comment by normanoffel** [comment]
First, I think there is a difference between Occupancy vs. Capacity. Are those terms defined in Transmodel? Are they used adequately in SIRI and NeTEx? Without consulting Transmodel: To my understanding, Capacity describes the options and extend to which a vehicle is able to transport passengers whereas Occupancy describes how the Capacity is used by passengers. In that sense you could argue that Occupancy could be extended to address each transporting option of the capacity description (Seating, Standing, SpecialPlace, ...) in the same way it does for the TotalCapacity which I think it currently does. But that is a discussion to be held within SIRI, is it not? Does OJP have other criteria/ideas/requirements?

**Comment by ue71603** [comment]
Christophe: There is a newer Siri version.

**Comment by ue71603** [comment]
Fixed by: https://github.com/VDVde/OJP/pull/264
