### ISSUE TITLE
Removing OJP_All.xsd and remove all circular dependencies

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#251]
If ok, we try to remove all circular dependencies and also OJP_All (which is the source of 95% of the circularity.

**Comment by sgrossberndt** [comment]
I don't understand this issue.
There are several issues in SIRI itself with circular references which lead to failures when verifying the schema.
The OJP_All.xsd was created to overcome the issues of circular dependencies. You just include OJP_All.xsd and are done with it.
I don't see how it is possible to fix the issues without changing SIRI source, which is not in our domain.

**Comment by ue71603** [comment]
Then we should remove includes that are not OJP_All.xsd. And the SIRI circular dependencies we need to address in SIRI.
David Rudi and I will have a look into it.

**Comment by ue71603** [comment]
Stefan: We should clean it up.

**Comment by ue71603** [comment]
there is a new issue open and we need for SIRI to fix this first. I close this one.
