### ISSUE TITLE
Documentation (HTML):  documentation on enums does not show

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#255]
<xs:enumeration value="leastWalking"/>
			<xs:enumeration value="leastCost"/>
			<xs:enumeration value="leastDistance">
				<xs:annotation>
					<xs:documentation>Least distance in meter. Mostly used for ALTERNATIVE MODE OF OPERATION</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="earliestArrival"/>

**Comment by trurlurl** [comment]
Solved with new Xcore documentation tool.
