### ISSUE TITLE
Should PlaceResult/Place also have a reference to a Situation

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#260]
OJPLocationInformationDelivery does have Situations in the Context. However, they are nowhere referenced in the rest of the result
Should we add such a reference for StopPlace/StopPoints?

**Comment by Aurige** [comment]
LIR ?

**Comment by ue71603** [comment]
Location Information Request

**Comment by ue71603** [comment]
create PR

**Comment by ue71603** [comment]
Exclude Situations must be also in LIR. Also in SER (StopEventFilterGroup)

**Comment by ue71603** [comment]
Addressed in: https://github.com/VDVde/OJP/pull/268
