### ISSUE TITLE
Is Exclude handled ideally in PtModeFilter

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#261]
Isn't it strange, that the PtModeFilter works with exclude and we name the element exclude?

Shouldn't it be an Include then?
![image](https://user-images.githubusercontent.com/24227470/199298734-58d4af25-6e7e-41ef-8cd9-0bc15737a2de.png)

**Comment by trurlurl** [comment]
Same as in TRIAS. As I understand it, the filter can be used in two ways: either to exclude all listed transport modes (default way, Exclude == true) or to include them (if Exclude == false).

Documentation text could be improved: How the filter shall restrict the search - whether by excluding or or by including the modes in the list. Default is true / exclude.

**Comment by ue71603** [comment]
only textually.

**Comment by ue71603** [comment]
fixed with https://github.com/VDVde/OJP/pull/266
