### ISSUE TITLE
Add formation information to OJP2.0

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#269]
Formation information should be added fully in documentation and in
* StopEvent
* TripInformation
* Trip with filter

we take the SIRI formation elements, if ok. This adds a lot of complexity. And I think we need a "IncludeFormation in the request as well with default "false".

One point would be Disruption/FormationCondition and more important the JourneyFormationGroup 

Part 1: Formation on the train
Part 2: Formation at stations (Calls  Arrival/Departure-FormationAssignment

**Comment by herlitze** [comment]
I talked to a specialist at our company who said that the SIRI structures for formations (JourneyFormationGroup) are very complex and the modeling is not always clear (e.g. changes of a formation within a journey). Could a subset be sufficient for OJP?

**Comment by ue71603** [comment]
I had today a discussion with Adrian. We believe that the SIRI 2.1 formation should be used. We may in the documentation show, how to use it in a simplified form (only some elements to be filled in). However:

- It is the format for Transmodel
- For accessibility complex things might be necessary.
- GTFS RT formation extension is no better in the end.

When this is agreed, I will copy things from the CEN SIRI European profile draft (information from Adrian).

For non-train SIRI proposes the usage of VehicleFeatureRef. We don't have that neither in OJP.

**Comment by ue71603** [comment]
I start with a PR for both those things and then we might continue. Unfortunately, currently it will reference a very old version of SIRI...

**Comment by ue71603** [comment]
will continue here: https://github.com/VDVde/OJP/pull/328
