### ISSUE TITLE
17. CEN document / spelling errors ?

### ISSUE THREAD

**Issue by BertRadi** [VDVde/OJP#27]
documentation issues will be added to the CEN document
[Documentation] tactilePatformEdges
[Documentation] DwellTime
[Documentation] InfoURL vs InfoUrl
[Documentation] DatedJourneyStructure
[Documentation] PathGuidanceSectionStructure
[Documentation] LegAlightStructure

**Comment by skinkie** [comment]
[Documentation] tactilePatformEdges: tacticlePlatformEdges
[Documentation] DwellTime: Cardinality 0:1
[Documentation] DatedJourneyStructure: BookingArrangementsContainer is in Errata
[Documentation] PathGuidanceSectionStructure: PathLink is in Errata
[Documentation] LegAlightStructure: Order is in Errata

[Documentation] InfoURL vs InfoUrl: This becomes very problematic if we change all camelcase Url's, it would also change the XSD on several places.

**Comment by sgrossberndt** [comment]
All documentation changes apart from InfoUrl have been fixed.

**Comment by sgrossberndt** [comment]
Fixed in documentation and https://github.com/VDVde/OJP/pull/31
