### ISSUE TITLE
Additional parameters to discuss

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#276]
Malte and Thomas will present some additional parameters for OJP 2.0 based on the User Preference discussion:

Will be translated
•	Tarifzonen einschliessen
•	Höhendaten berücksichtigen
•	ParkingOptionen, Echtzeit zu Parkhäuser
•	Routing unter Berücksichtigung Ladestationen unter Angabe Leistung/Steckertypen
•	LocationInformationRequest: Sortierung der Treffer, Berücksichtigung bestimmter Gebiete, Gewichtungen der StopType (Haltestellen höher gewichten als Adressen, best. Regionen höher gewichten)

**Comment by herlitze** [comment]
I created the following pull requests:
[added TariffzoneFilter to TripDataFilterGroup](https://github.com/VDVde/OJP/pull/282)
[added ConsiderElevationData](https://github.com/VDVde/OJP/pull/277)
[Parking options](https://github.com/VDVde/OJP/pull/280)
[added PlaceSortingGroup to PlaceParamStructure](https://github.com/VDVde/OJP/pull/281)

I hope we can discuss the additional parameters on this basis.

**Comment by ue71603** [comment]
PR done by Malte and Thomas
