### ISSUE TITLE
Solve merge conflicts on generated documentation in each branch

### ISSUE THREAD

**Issue by sgrossberndt** [VDVde/OJP#288]
The current situation is not good regarding the process to get a change merge ready. Each pull request / branch has to be checked out and changes_for_v1.1 has to be merged into it and requires another run of the ci job updating the generated documentation.

The reason the generated documentation is there in each branch / pull request is for people to be able to see the outcome of their XSD changes in the generated documentation.

I would like to propose a different concept here:
- for each branch generate the documentation like before but upload it to github pages only and do no longer store the generated/ folder in the repository at all
- in order for a branch not overwriting the main (changes_for_v1.1 / master / main) documentation each generated documentation has to have its own folder.

e.g.:
- https://vdvde.github.io/OJP/index.html (changes_for_v1.1 or whatever we decide is currently the "main" documentation
 - https://vdvde.github.io/OJP/branches/PtModeFilter_Improve_Docu/index.html (for the [PtModeFilter_Improve_Docu](https://github.com/VDVde/OJP/tree/PtModeFilter_Improve_Docu) branch)

What do you think about this?

**Comment by herlitze** [comment]
Sounds reasonable to me.

**Comment by ue71603** [comment]
Is also ok for me. Perhaps not having folders, but instead of index.html we use the <branch>.html. But you may do as you please. Will you use .ignore for the generated folder?
@skinkie your view?

**Comment by sgrossberndt** [comment]
If we would put them into the same folder, they would all share the asciidoc.css file. If we change anything in that file, it wouldbe changed for all files. Therefore I think having folders is a better option.

**Comment by ue71603** [comment]
Hi Stephan. Fine with me.

**Comment by sgrossberndt** [comment]
Sigh. Well. It works, but it doesn't. I am now able to deploy the generated index.html of a branch to subdirectory, but uploading this will replace the whole github-pages deployment. So the newly generated index.html in a subfolder is there but the former branches and the main index.html of the changes_for_v1.1-branch are gone then :-(

**Comment by sgrossberndt** [comment]
Another option would be to generate the index.html of each existing branch with every run. This may be some overhead, but it would work..
