### ISSUE TITLE
Should OJPFare OJPRefinement and OJPAvailability also provide a Context in the Request?

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#310]
We have some requests, where the input is a Trip. Should we also at least have to possibility to provde a TripContext? E.g. for the details of places?

**Comment by skinkie** [comment]
Interesting question. I would say that this would not be **required**, but may be _optional_. In my perspective (unique) references should be enough to pass the information through the system.

**Comment by ue71603** [comment]
done in multiple PR
https://github.com/VDVde/OJP/pull/321
https://github.com/VDVde/OJP/pull/322
