### ISSUE TITLE
Possible extensions of Traveller from analysing TOMP

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#311]
A traveller in TOMP has additional attributes, that might be of interest to OJP: 
* isValidated | booleanWhether this traveler's identity and properties have been verified by the MaaS provider
* referenceNumber | stringreference number of the traveler. This number could be used to refer to in the planning result.

**Comment by skinkie** [comment]
If @pvgrumbkow had been death, he would roll in his grave over the second suggestion ;-) This makes the requests GDPR sensitive.

**Comment by ue71603** [comment]
so we do only the first one?

**Comment by skinkie** [comment]
Would that first one make sense without a reference?

**Comment by ue71603** [comment]
I think that yes.  If I say, she has the necessary driving license, then it is my problem and no longer yours.

**Comment by skinkie** [comment]
Yes, but there are no 'authenticated' requests right?

**Comment by ue71603** [comment]
they are working locally and in relation to place the XSD is stored. If you want to do it 'authenticated' shouldn't we do that in a different PR.

**Comment by ue71603** [comment]
I think usually OJP work with known users only in production. I don't know of any OJP that accepts requests without authentication at some point.

**Comment by ue71603** [comment]
For what I do with fares I can work that is set the flag in TOMP to no.

**Comment by ue71603** [comment]
So we don't do neither currently.
