### ISSUE TITLE
Incomplete documentation tables for TopographicPlaceStructure and TopographicPlaceRefStructure

### ISSUE THREAD

**Issue by trurlurl** [VDVde/OJP#317]
See below:

https://vdvde.github.io/OJP/index.html#TopographicPlaceRefStructure

![grafik](https://user-images.githubusercontent.com/82838870/217365569-f0772a0a-6e02-4677-8ebc-4bd9bc33d009.png)

![grafik](https://user-images.githubusercontent.com/82838870/217364580-c6203d2d-23d3-4c57-b046-85688749ca84.png)

**Comment by sgrossberndt** [comment]
The second column [in the documentation of TopographicPlaceRefStructure](https://vdvde.github.io/OJP/#TopographicPlaceRefStructure) should contain the `TopographicPlaceCodeType` defined in https://github.com/VDVde/OJP/blob/changes_for_v1.1/OJP/OJP_PlaceSupport.xsd#L153 like it works for the `AddressCodeType` defined in https://github.com/VDVde/OJP/blob/changes_for_v1.1/OJP/OJP_PlaceSupport.xsd#L345 as can be seen [in the generated documentation of AddressRefStructure](https://vdvde.github.io/OJP/#AddressRefStructure)

**Comment by trurlurl** [comment]
Solved with new Xcore documentation tool.
