### ISSUE TITLE
Support for multiple languages in request and response

### ISSUE THREAD

**Issue by sgrossberndt** [VDVde/OJP#33]
https://github.com/VDVde/OJP/pull/32
https://github.com/VDVde/SIRI/pull/3

**Comment by sgrossberndt** [comment]
https://forum.vdv.de/viewtopic.php?f=88&t=202

**Comment by skinkie** [comment]
We suggest to wait for the SIRI extension, and if it is available to apply it.

**Comment by pvgrumbkow** [comment]
@skinkie 
Wasn't this addressed by pull request #32 ?
