### ISSUE TITLE
Add TripChangeRequest to Main Documentation

### ISSUE THREAD

**Issue by AndreasAtSBB** [VDVde/OJP#355]
Hello Norman

Can you add the documentation of the new defined TripChangerequest? 
Reference to #352 .
Later on also to new XSD description. I'll also add things in #245.

**Comment by AndreasAtSBB** [comment]
Some basic description for the TripChangeRequest were made.
Fields for the request and response are defined.
Close?

**Comment by ue71603** [comment]
Addressed. @trurlurl  did his part. @herlitze  has a look over the chapter.
