### ISSUE TITLE
Examples are missing the OJP xml wrapper?

### ISSUE THREAD

**Issue by skinkie** [VDVde/OJP#358]
https://github.com/VDVde/OJP/blob/changes_for_v1.1/examples/functions/fare/FareResponse.xml

vs 

https://github.com/VDVde/OJP/blob/changes_for_v1.1/examples/functions/error/error_response.xml

**Comment by ue71603** [comment]
strangly they work.....

**Comment by ue71603** [comment]
https://github.com/VDVde/OJP/pull/359
