### ISSUE TITLE
Question: ContinuousLeg or TimedLeg for demand responsive area buses

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#360]
According to a quick discussion with Malte and Norman, it seems that these are still TimedLeg(s) as soon as they are "scheduled". Without opposition that will go into the descriptions.

**Comment by skinkie** [comment]
![image](https://github.com/VDVde/OJP/assets/502394/ca737902-2842-4cb7-b615-972d3e2e3952)
Kasia would like to have feedback, the diagram is incorrect for what we have discussed here.

**Comment by ue71603** [comment]
Nice, I answered that question already twice to her.

**Comment by ue71603** [comment]
solved so far.
