### ISSUE TITLE
TYPE OF GUARANTEE

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#363]
We discussed adding TYPE OF GUARANTEE in OJP as part of the TripResult. However, it is unclear to me, what TYPE OF GUARANTEE really does in Transmodel and what its content are.

**Comment by Aurige** [comment]
If I remember properly, the TYPE OF GUARANTEE is quite generic (it is a specialisation o a TYPE OF VALUE) and has a relation with a CONNECTION LEG of a TRIP. As a TYPE OF VALUE, it will require some agreement (in profile or between end points) to define the meaning of selected values. However, most the the guarantee information is already in the underlaying NeTEx info (in CONNECTION or in TRANSFER).

**Comment by ue71603** [comment]
I think that we leave it be then.
