### ISSUE TITLE
Undefined delay on a leg and the information that the connection can't be guaranteed

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#382]
From Andreas Schlapbach I got asked, 
1. whether we can inform about an undefined delay on a leg
2. whether we can provide the information that a connection can't be guaranteed.

### Considering 1
* Currently available is a PtSituation with Consequences/Delays

Our current model would probably assume that this type of leg would never show up in a response. It could happen during refinement, so we might need to deal with it more directly.

So I propose to update ServiceStatusGroup with UndefinedDelay boolean

### Considering 2
This certainly should be part of the TransferLeg.  Perhaps something can be done with Situation.

But we might add information about the Interchange to TransferLegStructure :
* add InterchangeGroup after TransferDurationGroup in TransferLegStructure
* the InterchangeGroup consists of:
* * InterchangeCode
* * InterchangeRef
* * ExtraInterchange
* * Cancellation
* * InterchangePropertyGroup

**Comment by herlitze** [comment]
Regarding 2
When can a connection be guaranteed/not guaranteed? In my understanding there are guaranteed connections where they wait on the feeder. This would be a flag showing a guaranteed connection.
Or does this refer to a request with useRealtimeData:explanatory, where a change with the current delay is no longer possible?

**Comment by ue71603** [comment]
@herlitze  The idea is to have a guaranteed connection, that is no longer guaranteed (because the delay of the feeder is too great, breaking the interchange "contract").
