### ISSUE TITLE
Dogs and bicycle on the trip

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#385]
In ticketing dogs and bicycles result in additional tickets and sometimes reservations. Should we include it into the OJPFare request.
We already have a bikeProfile and we have the AccessMode bicycle. Should we expand and also include dogs? For the search or only for OJP Fares?

@herlitze  @sgrossberndt @skinkie  @normanoffel @JonaVBB

**Comment by skinkie** [comment]
I think they may be added.

**Comment by herlitze** [comment]
I agree, is there the need for them in the search? Are there certain means of transport in which dogs are not allowed, as in the case of taking a bike?

**Comment by ue71603** [comment]
@herlitze  I think we need dog/bicycle as an addition to OJPFareRequest.  i don't think that we have detail information about dogs in the trip service.

**Comment by ue71603** [comment]
processed here: https://github.com/VDVde/OJP/pull/389
