### ISSUE TITLE
Origin and Destination in DatedJourneyGroup

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#393]
Came up during work for https://github.com/VDVde/OJP/pull/387

We have Origin/Destination (as text and ScheduledStopPoint) now in Service and ServiceSection. It is mandatory always.

Problems arising:

1. Duplication
In many cases just duplicates data. However, in some uses it might be useful. E.g. joint trains. The front of the train might show  "Murten/Neuchâtel". The individual compositions "Murten" and Neuchâtel.

2. Origin not that import
Might it be a good idea to make the origin optional in Service and ServiceSection?

3. Origin/Destination problematic for SINGLE JOURNEYs
Currently the assumption is always that we have a classic public transport. Showing stuff on the front of the vehicle is important. What do we show in a demand responsive bus or a taxi or a vehicle-pooling.  Having mandatory text there makes no sense.
If we agree that Orign/Destination are mandatory, then DatedJourneyGroup probably needs to be changed for some cases. Should we do that or having origin/destination be optional in any case?

**Comment by herlitze** [comment]
I would remove origin and destination from the service to avoid these problems. And make them optional in the sections.

1. Isn't the front of the train also the front of one of the compositions? The clients could display "Murten/Neuchâtel" by reading the sections of the individual compositions.

**Comment by ue71603** [comment]
will do.

**Comment by ue71603** [comment]
fixded with new commit to https://github.com/VDVde/OJP/pull/387
