### ISSUE TITLE
Pull master in 1.1?

### ISSUE THREAD

**Issue by skinkie** [VDVde/OJP#40]
@sgrossberndt could you pull master in 1.1 so this change is also in?

https://github.com/VDVde/OJP/commit/92248dd09f85461f2f7a07375b3600afba2d2378

**Comment by skinkie** [comment]
@sgrossberndt could you look into this?

**Comment by sgrossberndt** [comment]
There are two options to do so:

1. merge master into changes_for_v1.1
![merge_master](https://user-images.githubusercontent.com/3786510/73348316-79d24e80-4289-11ea-9ff4-0acf3ed5306b.png)
2. rebase changes_for_v1.1 on master
![rebase_on_master](https://user-images.githubusercontent.com/3786510/73348317-7a6ae500-4289-11ea-98f6-8679825a31b5.png)

**Comment by sgrossberndt** [comment]
1. keeps the current history intact and makes the process visible more clearly
2. contains a clean history but requires a force push to changes_for_v1.1

**Comment by sgrossberndt** [comment]
We decided on option 1

**Comment by sgrossberndt** [comment]
done in https://github.com/VDVde/OJP/commit/6dd0ae68a88208e246353e8b6efaefd3bee81a74
