### ISSUE TITLE
TRAVEL and OJPFare

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#408]
(a) I was considering, whether we would need TravelId and TravelOrder to in TripResult so that OJP can built an aggregate price. However, it seems to me that is exactly what MultipTripFareRequest should do. Do you agree? Then I would improve the definition to make it clear, that all single trips need to be part of a TRAVEL and are priced as one in the most optimal way.

(b) We currently have no mechanism to price e.g. park&ride.  A TripResult doesn't provide enough information for that (the time the car stays at the park&ride is not clear). Should we add something there? E.g. for 2.1?

**Comment by skinkie** [comment]
Do you mean here that you want to have the travels to be priced as composite? For example allow fare capping?

**Comment by ue71603** [comment]
> Do you mean here that you want to have the travels to be priced as composite? For example allow fare capping?

Sometimes people want return prices.  Also in the case of planes:  single/single return or having multiple parts significantly affects the price.   And we otherwise never modeled TRAVEL.

**Comment by trurlurl** [comment]
> This can be modeled with MultTripFareRequest. This means it is ok and we don't need it. @trurlurl do we need to state that somewhere in the documentation about the fare service?

I think the existing text covers that: "The difference between MultiTripFareRequestStructure and TripFareRequestStructure lies in the point that the server – in case of a MultiTripFareRequestStructure – is requested to find a fare product combination covering all trips that is as economic as possible, for example, a day fare product if enough trips are on the same day."
