### ISSUE TITLE
Restricted lines & MultiPointTripRequest

### ISSUE THREAD

**Issue by trurlurl** [VDVde/OJP#424]
Is it ok that IncludeAllRestrictedLines and PassengerCategory (TripPolicyGroup) is not available for MultPointTripRequest? 

How ist MultiPointTripRequest supposed to behave - does it simply not support restricted lines, or should it always include all restricted lines and continue the search until solutions for each variant have been found? Or should it become possible to hand over the parameters?

**Comment by ue71603** [comment]
We could argue both ways (as those things don't really make sense in a distributed environment. However, currently it is just neglicence from my point of view. @skinkie @herlitze  Should we add it there or add an argumentation why it is not there?

**Comment by herlitze** [comment]
I agree with both of you and would add the parameters.
