### ISSUE TITLE
Handling of MultiPointType: urgent answer required

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#442]
Austria noted: 

> Made MultiPointType a required parameter in
> OJPMultiPointTripRequest. #353
> Auf Basis dieser Definition (die jedenfalls Sinn macht, wenngleich die von einem passiven Knoten unterstützten MultiPointTypes ohnehin vorab abgeklärt werden müssen) ist der Parameter MultiPointType in Chapter 8.6.4.5 MultiPointTripParamStructure in Table 151Description of MultiPointTripParamStructure als mandatory angeführt.
> 
> Allerdings sind die Params in denen sich der MultiPointType versteckt laut Chapter 8.6.4.3 OJPMultiPointTripRequestStructure und Table 149 Description of OJPMultiPointTripRequestStructure optional.

The parameter IS optional. and marked that way.
In TripRequest "anyPoint" is the the default value that should be implemented.

In the response it is noted, that it "should" be returned. In my view this might be enough.
Different opinions?

Urgent answers needed.
![image](https://github.com/VDVde/OJP/assets/24227470/f042f48e-86e1-4870-9829-31eb6065198e)

Andrés proposal:

> I agree with the Austrian comment, there is indeed an incoherence and it can be found in the code and the documentation. 
> Correcting it would be simple: setting the cardinality of the Params element in MultiPointTripRequest to 1:1 (instead of 0:1).
> The currently existing inconsistency shows that a certain parameter (MultiPointType) was intended to be a required (non-optional) parameter, but this is not fully implemented / guaranteed by the code.
> P.S. Before applying the change - should we check and discuss whether having it a required parameter is really the right decision - a previous solution (CR #98, still mentioned in the changelog and misleading/superfluous if a required parameter) was to have a default value (anyPoint)? Depending on the decision, I think the changlog entry should be removed.

**Comment by ue71603** [comment]
Stefan/Matthias: Let's also have a default in the response. And update the Changelog (that it is optional with default value)

**Comment by herlitze** [comment]
@ue71603 Do I understand you correctly that you want to keep the OJPMultiPointTripRequest.Params optional and also want to keep OJPMultiPointTripRequest.Params.MultiPointType required? 
The changes you are suggesting are adapting the documentation accordingly and adding a default value to the response (OJPMultiPointTripDelivery.MultiPointType)?
This would be fine for me.

**Comment by ue71603** [comment]
@herlitze  that is exactly what I intend to do...

**Comment by ue71603** [comment]
addressed in https://github.com/VDVde/OJP/pull/443

**Comment by sgrossberndt** [comment]
> @ue71603 Do I understand you correctly that you want to keep the OJPMultiPointTripRequest.Params optional and also want to keep OJPMultiPointTripRequest.Params.MultiPointType required? The changes you are suggesting are adapting the documentation accordingly and adding a default value to the response (OJPMultiPointTripDelivery.MultiPointType)? This would be fine for me.

[In the current state `OJPMultiPointTripRequest.Params.MultiPointType` no longer is required](https://github.com/VDVde/OJP/pull/443/files#diff-231d41fa75aa5fbc0757e95a629f845d7143dbb82f7943636c37fd0e3259729bR1383). Is that how it is supposed to be? @herlitze @ue71603

**Comment by herlitze** [comment]
@sgrossberndt I don't remember any reason for this and I didn't find any reason in the comments either.
@ue71603 Was this done intentionally?
