### ISSUE TITLE
Investigate the generation of tables from XSD 

### ISSUE THREAD

**Issue by skinkie** [VDVde/OJP#45]

**Comment by skinkie** [comment]
It has been discussed that @pvgrumbkow will provide an internal XSLT. @skinkie will test it on the current XSDs of the project.

**Comment by pvgrumbkow** [comment]
XSL delivered.

**Comment by skinkie** [comment]
@skinkie wil try to create tables.

**Comment by sgrossberndt** [comment]
@skinkie Could you please add a branch containing the script to generate the tables you currently have (as discussed in the last meeting)? We could work together to fix the issues @pvgrumbkow mentioned:

> 1) Enumerations should list their possible values.
> 2) The cardinality of elements (0..1, 1..unbounded, etc.) should get a separate column or be part of the type column.
> 3) Non-optional elements should be written in bold.
> 4) Is it possible to introduce links for each reference of a type to its definition?
> 5) For ExchangePointsParamStructure neither type column nor comment column were generated. Why is that? Might be related to 7.
> 6) The toplevel element definitions should get an appropriate text.
> 7) For ExchangePointsRequestStructure the table looks somewhat messed up. Might be related to 5.
> 8) For type definitions containing only one element, nevertheless a complete table should be generated.
> 9) Annotations on toplevel (for types or elements) should appear as normal text (not as code citation) underneath the title of the defined element. The text "The element contains..." should be added without a new line.
> 10) I would prefer tables also for choices. Perhaps they can be somehow made distinctive to the sequence tables.
> 11) For LocationInformationRequestGroup apparently something like sub-tables should have been generated. A good idea, but apparently the layout of these did not work.
> 12) The sorting of the chapters was done in alphabetical order? I would prefer the sorting from the XSD file.
> 13) Probably we will need some kind of chapter numbers. Perhaps each file gets one chapter number and all definition in that file get the appropriate sub-numbers?

**Comment by ue71603** [comment]
@skinkie  Is this still open? I think this is done. Can you close it then?
