### ISSUE TITLE
Documentation request: No Sight

### ISSUE THREAD

**Issue by skinkie** [VDVde/OJP#46]
#36 has been merged in version 1.1. The documentation should still be added.

**Comment by sgrossberndt** [comment]
It is documented in 
https://github.com/VDVde/OJP/blob/changes_for_v1.1/CHANGELOG.md
and
https://vdvde.github.io/OJP/generated/OJP.html#BaseTripMobilityFilterGroup

**Comment by trurlurl** [comment]
Label *documentation* removed, also updated Word document.
