### ISSUE TITLE
Section definition from TRIAS

### ISSUE THREAD

**Issue by JonaVBB** [VDVde/OJP#47]
Extension for OJP v2.0

Take over the section definition from TRIAS, in order to allow changes of service parameters through a leg.

**Comment by ue71603** [comment]
@JonaVBB  Can you briefly describe, what should go into the Pull Request? e.g. copying the relevant parts into this issue?

**Comment by JonaVBB** [comment]
Actually this input came from @pvgrumbkow. I was only the one who wrote it down.

**Comment by ue71603** [comment]
@kgrimme @herlitze : Has one of you insights what Peter wanted here?

**Comment by ue71603** [comment]
@JonaVBB : Peter is no longer working on this topic.

**Comment by JonaVBB** [comment]
> @JonaVBB : Peter is no longer working on this topic.

I know. :-(

**Comment by ue71603** [comment]
Stephan: ICE from Berlin that is separated at some point. There was an issue, when the train is separated one may have no restaurant in one part. @normanoffel : Can you ask Peter?

**Comment by pvgrumbkow** [comment]
Sorry for the confusion.
Beginning with TRIAS v1.3 we introduced within the DatedJourneyStructure a sequence of ServiceSections. The idea was the following: properties of a dated service can change on its path. E.g. the service name "ICE 884", the direction "München", or even the mode of the service can change on its path. For this purpose in TRIAS v1.3 the sections allow to divide the service into sections with different properties.
Please have a look into DatedJourneyStructure and ServiceSectionStructure in TRIAS to decide, whether this extension also fits to OJP. My personal opinion is yes obviously.

**Comment by ue71603** [comment]
After understanding what it is, I see the need as well. We need it to make sure we can have the fares right for such things. Also international trains might be handled better that way.

**Comment by ue71603** [comment]
solved in: https://github.com/VDVde/OJP/pull/263/files
