### ISSUE TITLE
URL pointing to a fully responsive webview

### ISSUE THREAD

**Issue by JonaVBB** [VDVde/OJP#49]
Change of documentation for OJP v1.1

The field FareProductStructure.FareProductBookingGroup.SaleUrl should be declared in the documentation, to contain an URL pointing to a fully responsive webview, which can be used within any container. The webview itself should contain further ticketing information and/or the possibility to sell the ticket. The URL can also be a universal link URL, which automatically redirects to the correct ticketing platform, depending on used OS and context.

**Comment by pvgrumbkow** [comment]
A more flexible method would be the following:
Introduce a flag into WebLinkStructure, which transports the type of the object, where the URL is pointing to. This could be a MIME type, or it could be something self defined. Important would be to know, whether a URL destination is fully responsive and can therefore be embedded as a webview into apps or web pages.
