### ISSUE TITLE
MinimizeResponseContext

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#64]
I thought that in some use cases the client does not need all the ResponseContext, it could be omitted (at least all information about the stops).

Unfortunatley I don't have enough rights to create a pull request.

**Comment by ue71603** [comment]
[Changed_Files.zip](https://github.com/VDVde/OJP/files/4237325/Changed_Files.zip)

**Comment by sgrossberndt** [comment]
You can always create a fork of a repository, prepare a change in a branch there and create a pull request.

**Comment by sgrossberndt** [comment]
I have additionally re-sent the invitation to join VDV.

**Comment by ue71603** [comment]
Pull request created for the thing.
