### ISSUE TITLE
Typo in 8.7.4.8

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#67]
![typo_ojp](https://user-images.githubusercontent.com/24227470/76073616-2f37a680-5f9a-11ea-9309-402a0b4a7dec.PNG)

**Comment by pvgrumbkow** [comment]
Will be handled by automatic documentation generation.

**Comment by sgrossberndt** [comment]
Solved with #154

**Comment by trurlurl** [comment]
Removed *documentation* label - completed.
