### ISSUE TITLE
StopEventRequest add a Param that allwas to include the hierarchy

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#69]
Add a parameter IncludeHierarchy in StopEventRequest that allows to include parts or all of the hierarchy of the stop point/stop place if known. So if you only know one stop point in the meta station, it can grab all data, if this is intended.

It has three values:
* no (default)
* down (includes all lower StopPoints/StopPlaces) according to the stop hierarchy. 
* all (includes all StopPoints/StopPlaces in the meta station)

If this is ok with you, I can create a pull request

**Comment by ue71603** [comment]
Param IncludeAssociatedStops. The actual association is done by the system.  No default. When not set, then the service behaves a sit usually. StopEventDataFilter.

**Comment by pvgrumbkow** [comment]
Handled by pull request #96
