### ISSUE TITLE
ErrorCondition

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#93]
The text in ErrorCondition ist misleading or needs to be completed.

E.g. can the Status be true and an ErrorCondition set, which would mean it is a warning.
Also: The text talks of multiple conditions, but the cardinality is one.

If you agree, I can create a PullRequest for this.
also there is a typo to be corrected.

**Comment by pvgrumbkow** [comment]
Could you be more specific to which ErrorConditions you refer? As there is no extra Warning field, the ErrorCondition is meant to transport also warnings.

**Comment by ue71603** [comment]
The structure is
![image](https://user-images.githubusercontent.com/24227470/91166227-557d0a00-e6d2-11ea-8852-d4101d1b2984.png)

in text
<xsd:group name="ServiceDeliveryRequestStatusGroup">
		<xsd:annotation>
			<xsd:documentation>Status Information for overall request. Specific error conditions will be given on each individual request.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Status" type="xsd:boolean" default="true" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Whether the complerte request could be processed successfully or not. Default is 'true'. If any of the individual requests within the delivery failed, should be set to ' false'.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="ErrorCondition" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Description of any error or warning conditions that appluy to the overall request. More Specific error conditions should be included on each request that fails.</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:choice>
							<xsd:element ref="CapabilityNotSupportedError"/>
							<xsd:element ref="OtherError"/>
						</xsd:choice>
						<xsd:element name="Description" type="ErrorDescriptionStructure" minOccurs="0">
							<xsd:annotation>
								<xsd:documentation>Text description of error.</xsd:documentation>
							</xsd:annotation>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:group>

The question is whether Status=true and ErrorsSet at the same time is a good idea.
Also: Status is set globally. What if individual responses were successful. Should you try to work through the response or give up, when you encounter a Status=false.

**Comment by ue71603** [comment]
Meetng 28.8. When status = true and ErrorConditions means a Warning. And correct typo.

When status = false, what to do with the result.
In the payloads there is a special group. In the main group if one fails, then you should still analyse the responses and use the status. 

==> bring this up with the SIRI working group.

**Comment by ue71603** [comment]
Will be included in SIRI that way.
